Cooking/routes/web.php
<?php

// Route::get('/', function () {
//     return view('welcome');
// });


// Route::get('/', function() {
//     return view('welcome');
// });

// Route::get('/', function() {
//     return view('blog.home');
// });

// Route::get('/', 'PostController@publicHomePage');

Route::get('/', 'PostController@publicHomePage');

Auth::routes();

Route::get('profile', 'UserController@profile')->name('profile');

Route::post('profile', 'UserController@update_avatar');

Route::get('/home', 'HomeController@index');

Route::resource('posts', 'PostController');

Route::get('/post/{name}', 'PostController@category')->name('category.show');

Route::get('/post/home', 'PostController@publicHomePage')->name('post.publicHomePage');

// Route::get('/posts/show', 'CommentController@show')->name('posts.show');
// Route::POST('post/signin/{id}','Postcontroller@show')->name('post.view_post');

Route::post('/comment/store', 'CommentController@store')->name('comment.add');

Route::post('/reply/store', 'CommentController@replyStore')->name('reply.add');

Route::get('/comment/delete/{id}', 'CommentController@delete')->name('comment.delete');

Route::post('/like', 'PostController@likePost')->name('like');

Route::get('/post/like/{id}', 'LikeController@addlike')->name('like.addlike');
Route::get('/post/unlike/{id}', 'LikeController@unlike')->name('like.unlike');
// Route::get('posts', 'PostController@index');

Cooking/resources/views/adminPanel/create.blade.php
@extends('layouts.template')

@section('title', 'Add New Blog Post')

{{-- <link rel="stylesheet" type="text/css" href="{{url('css/up_image.css')}}"/>
<script src="{{url('js/up_image.js')}}"></script> --}}

@section('content')
  <div class="col-md-12">
  <h1>สร้างโพสต์เมนูอาหาร</h1>
    <hr style="width: 1000">
  @if (count($errors) > 0)
    <div class="alert alert-danger">
      <strong>Whoops!</strong> There were some problems with your input.<br><br>
      <ul>
        @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
        @endforeach
      </ul>
    </div>
    @endif
    @if(session('success'))
      <div class="alert alert-success">
         {{ session('success') }}
      </div>
    @endif
  <div class="col-sm-12 col-sm-offset-2">
    <form action="{{ route('posts.store') }}" method="post" enctype="multipart/form-data">
      {{ csrf_field() }}

      <div class="form-group">
        <label for="title">ชื่อเมนู :</label>
        <input name="title" type="text" class="form-control">
      </div>

      <div class="form-group">
        <label for="title">เลือกประเภทอาหาร :</label>
        <select class="form-control" name="category">
            <option disabled selected>เลือกประเภทอาหาร</option>
            <option value="อาหารหวาน" name="อาหารหวาน">อาหารหวาน</option>
            <option value="อาหารคาว">อาหารคาว</option>
            <option value="เครื่องดื่ม">เครื่องดื่ม</option>
        </select>
     </div>
      <br>
       <div class="form-group">
        <label for="equipment">อุปกรณ์ :</label>
        <textarea name="equipment" type="text" class="form-control"></textarea>
      </div>

      <div class="form-group">
            <label for="garnish">วัตถุดิบ :</label>
            <textarea name="garnish" type="text" class="form-control"></textarea>
          </div>

      <div class="form-group">
        <label for="body">วิธีการทำ :</label>
        <textarea name="body" id="" name="body" cols="30" rows="10" class="form-control"></textarea>
      </div>

      {{-- <div class="form-group">
            {{Form::label('body', 'Body')}}
            {{Form::textarea('body', '', ['id' => 'article-ckeditor', 'class' => 'form-control', 'placeholder' => 'Body Text'])}}
        </div> --}}

      <div class="input-group">
        {{-- <div class="custon-file">

            <input type="file" class="custom-file-input" name="image" id="exampleFormControlFile1">
            <label class="custom-file-label" for="exampleFormControlFile1"><b>รูปภาพประกอป</b></label>
        </div> --}}

      </div>
      <div class="input-group">
        <label for="exampleFormControlFile1">เลือกรูปภาพ</label>
        <input type="file" name="image" class="form-control-file" id="exampleFormControlFile1">
      </div>
      {{-- <br><div class="container">
        <div class="row">
        <div class="col-sm-2 imgUp">
          <div class="imagePreview"></div>
        <label class="btn btn-primary">
            Upload<input type="file" class="uploadFile img" value="Upload Photo" style="width: 0px; height: 0px; overflow: hidden;">
        </label>
        </div><!-- col-2 -->
        <i class="fa fa-plus imgAdd"></i>
       </div><!-- row -->
      </div><!-- container --> --}}
      <hr>
      <button type="submit" class="btn btn-primary">โพสต์</button>
      <a class="btn btn-default pull-right" href="{{ route('posts.index') }}"><i class="fa fa-arrow-left" aria-hidden="true"></i>  Go Back</a>
    </form>
  </div>
</div>

{{-- <script src="/vendor/unisharp/laravel-ckeditor/ckeditor.js"></script> --}}
@section('js')
<script>
        CKEDITOR.replace('article-ckeditor', {
          height: 400,
        });
      </script>
       {{-- <script>
            CKEDITOR.replace('editor1', {

              toolbarGroups: [{
                  "name": "basicstyles",
                  "groups": ["basicstyles"]
                },
                {
                  "name": "links",
                  "groups": ["links"]
                },
                {
                  "name": "paragraph",
                  "groups": ["list", "blocks"]
                },
                {
                  "name": "document",
                  "groups": ["mode"]
                },
                {
                  "name": "insert",
                  "groups": ["insert"]
                },
                {
                  "name": "styles",
                  "groups": ["styles"]
                },
                {
                  "name": "about",
                  "groups": ["about"]
                }
              ],

              removeButtons: 'Underline,Strike,Subscript,Superscript,Anchor,Styles,Specialchar'
            });
          </script>
<script>
        CKEDITOR.replace('article-ckeditor', {
          height: 200,

          removeButtons: ''
        });
      </script> --}}
{{-- <script>
        CKEDITOR.replace( 'article-ckeditor', {
            extraPlugins: 'mathjax',
            mathJaxLib: 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS_HTML',
            height: 320,
            extraPlugins: 'autogrow',
            autoGrow_minHeight: 200,
            autoGrow_maxHeight: 600,
            autoGrow_bottomSpace: 50,
            removePlugins: 'resize',
            height: 200,
            removeButtons: '',
            0extraPlugins: 'widget',
            height: 300,
            height: 250,
            extraPlugins: 'colorbutton',
            colorButton_colors: 'CF5D4E,454545,FFF,CCC,DDD,CCEAEE,66AB16',
            colorButton_enableAutomatic: false
        } );
</script> --}}
@endsection
<script type="text/javascript">

    $(document).ready(function() {

      $(".btn-success").click(function(){
          var html = $(".clone").html();
          $(".increment").after(html);
      });

      $("body").on("click",".btn-danger",function(){
          $(this).parents(".control-group").remove();
      });

    });

</script>

@endsection

Cooking/resources/views/adminPanel/edit.blade.php
@extends('layouts.template')

@section('title', 'Add New Blog Post')

@section('content')
  <div class="continer">
  <h1>เเก้ไข Blog Post</h1>
  @if(count($errors) > 0)
  <div class="alert alert-danger">
    <ul>
      @foreach($errors->all() as $error)
      <li>{{$error}}</li>
      @endforeach
    </ul>
  </div>
  @endif

  <div class="col-sm-12 col-sm-offset-2">
    <form action="{{action('PostController@update',$id)}}" method="post">
      {{ csrf_field() }}

      <div class="form-group">
        <label for="title">Title:</label>
        <input name="title" type="text" class="form-control" value="{{$post->title}}">
      </div>


      <div class="form-group">
        <label for="category">เลือกประเภทอาหาร :</label>
        <select class="form-control" name="category" value="{{$post->category}}">
            <option disabled selected>เลือกประเภทอาหาร</option>
            <option value="{{$post->category}}" name="{{$post->category}}">{{$post->category}}</option>
            <option value="อาหารหวาน" name="อาหารหวาน">อาหารหวาน</option>
            <option value="อาหารคาว">อาหารคาว</option>
            <option value="เครื่องดื่ม">เครื่องดื่ม</option>
        </select>

        <div class="form-group">
            <label for="equipment">อุปกรณ์ :</label>
            <input name="equipment" type="text" class="form-control" value="{{$post->equipment}}">
          </div>

          <div class="form-group">
                <label for="garnish">วัตถุดิบ :</label>
                <input name="garnish" type="text" class="form-control" value="{{$post->garnish}}">
              </div>


      <div class="form-group">
        <label for="body">วิธีทำ:</label>
        <textarea name="body" id="" cols="30" rows="10" class="form-control" >{{$post->body}}</textarea>
      </div>


    </div>
    {{-- <div class="input-group">
      <label for="exampleFormControlFile1">เลือกรูปภาพ</label>
      <input type="file" name="image" class="form-control-file" id="exampleFormControlFile1" >
      <br>
      <img src="{{ asset('images/' . $post->image) }}" alt="IMG-OUR">
    </div> --}}

      <button type="submit" class="btn btn-primary">Submit</button>
      <input type="hidden" name="_method" value="PATCH" />
      <a class="btn btn-default pull-right" href="{{ route('posts.index') }}">Go Back</a>
    </form>
  </div>
  <br>
  <div class="alert alert-danger">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <p><b>เขียนโพสเมื่อ : </b>{{ date('M j, Y h:ia', strtotime($post->create_at)) }}</p>
    <p><b>อัพเดตโพสเมื่อ : </b>{{ date('M j, Y h:ia', strtotime($post->updated_at)) }}</p>
  </div>

</div>
@endsection

Cooking/resources/views/adminPanel/home.blade.php
@extends('layouts.template')

@section('title', 'Blog Admin Panel')

@section('content')
  <h1>&nbsp;หน้าการจัดการ Blog</h1>
  <hr>
  @if(count($errors) > 0)
<div class="alert alert-danger">
  <ul>
    @foreach($errors->all() as $error)
    <li>{{$error}}</li>
    @endforeach
  </ul>
</div>
@endif

@if(\Session::has('success'))
<div class="alert alert-success">
  <p>{{ \Session::get('success') }}</p>
</div>
@endif

<div class="container-fluid">
    <a href="http://localhost:8000" class="btn btn-danger btn-sm">Go Back To Homepage : กลับหน้าหลัก</a>
    <br>
<br>
  <nav class="navbar navbar-expand-lg  bg-warning navbar-light">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <!-- <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-success my-2 my-sm-0" type="submit">Search</button>
        </form> -->
        <a href="{{ route('posts.create') }}"  class="btn btn-primary pull-right" ><i class="fa fa-plus" aria-hidden="true"></i> Add New Blog Post</a>
        <ul class="navbar-nav ml-auto">
                <li class="nav-item dropdown">
                    <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                        {{ Auth::user()->name }} <span class="caret"></span>
                    </a>

                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{{ route('logout') }}"
                           onclick="event.preventDefault();
                                         document.getElementById('logout-form').submit();">
                            {{ __('Logout') }}
                        </a>

                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                            @csrf
                        </form>
                    </div>
                </li>

        </ul>
      </div>
  </nav>

  <!-- <a href="{{ route('posts.create') }}"  class="btn btn-primary pull-right">Add New Blog Post</a> -->
  <br>

  <table class="table">
    <center><thead>
      <th>id</th>
      <th>title</th>
      <th>body</th>
      <th>image</th>
      <th>create_at</th>
      <th>edit</th>
      <th>delete</th>
    </thead>
  </center>
    <tbody>
      @foreach($posts as $post)
      <tr>
        <th>{{  $post->id }}</th>
        <td>{{ $post->title }}</td>
        <td>{{ strip_tags($post->body) }}</td>
        {{-- images --}}

         {{-- <td><img src="{{ URL::to('/') }}//images/{{ $post->image }}" class="img-thumbnail" width="75" alt="Don't have images to show."></td> --}}
         <td><img src="images/{{ $post->image }}" class="img-thumbnail" width="75" alt="Don't have images to show."></td>
         <td>{{ date('M j, Y h:ia', strtotime($post->create_at)) }}</td>
        <td><a href="{{action('PostController@edit',$post['id'])}}" class="btn btn-warning" data-toggle="tooltip" title="เเก้ไข">Edit</a></td>
        <td>
          <form method="post" class="delete_form" action="{{action('PostController@destroy',$post['id'])}}">
               {{ csrf_field() }}
               <input type="hidden" name="_method" value="DELETE">
               <button href="#" class="btn btn-danger delete_form" data-toggle="tooltip" title="ลบ !!">
                 Delete
               </button>
          </form>
        </td>
      </tr>
      @endforeach
    </tbody>
  </table>
</div>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script type="text/javascript">
    $(document).ready(function(){
      $('.delete_form').on('submit',function(){
        if(confirm("คุณต้องการลบข้อมูลหรือไม่ ?")) {
          return true;
        }
        else {
          return false;
        }
      });
    });
  </script>

<script>
        $(document).ready(function(){
          $('[data-toggle="tooltip"]').tooltip();
        });
</script>
@endsection